version: '3.9'

services:
  product-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - consul
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_HTTPS_PORT=https://+:5001      
      # - ASPNETCORE_URLS=http://+:5000   
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    networks:
      - product-network

  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0
    networks:
      - product-network

networks:
  product-network:
    driver: bridge