global using System.ComponentModel.DataAnnotations;
global using AppMicroServiceBuildingBlock.Contract.ApplicationContracts.Contracts;
global using AppMicroServiceBuildingBlock.Contract.ApplicationContracts.Contracts.Interfaces;
global using AppMicroServiceProduct.Domain.Brands;
global using FluentValidation;
global using AppMicroServiceBuildingBlock.Shared.Utilities;
